pragma Singleton
import QtQuick 2.11

QtObject {
    readonly property string ayasofya: "<b>The</b> <i>Hagia Sophia</i>, one of the historical architectural wonders that still remains standing today, has an important place in the art world with its architecture, grandness, size and functionality."
    readonly property string kizkulesi: "The Maiden's Tower (Turkish: Kız Kulesi), also known as Leander's Tower (Tower of Leandros) since the medieval Byzantine period, is a tower lying on a small islet located at the southern entrance of the Bosphorus strait 200 m (220 yd) from the coast of Üsküdar in Istanbul, Turkey."
    readonly property string sultanahmet: "The Sultan Ahmed Mosque or Sultan Ahmet Mosque (Turkish: Sultan Ahmet Camii) is a historic mosque located in Istanbul, Turkey. A popular tourist site, the Sultan Ahmed Mosque continues to function as a mosque today; men still kneel in prayer on the mosque's lush red carpet after the call to prayer. The Blue Mosque, as it is popularly known, was constructed between 1609 and 1616 during the rule of Ahmed I. "
    readonly property string skylandtower: "The project Skyland Towers is located in Istanbul, Turkey. The building complex with its three towers is a multi-storey mixed use development. Two towers reach a height of 293.1 m each – one of these towers is for residential use, the other for office spaces. The third tower is 179.1 m high and will be used as a hotel. The façade of all three towers is engineered by Werner Sobek. The aim is to create a highly efficient façade having a minimum impact on natural resources while offering a maximum of comfort to the users. Regional products and availability as well as resources are considered to help keeping expenses at a minimum. Once completed, the Skyland Towers will be the tallest skyscrapers in Turkey."
}
